server:
  port: 8753

spring:
  application:
    name: feign-server
eureka:
    client:
      serviceUrl:
      #注册中心地址，其他服务指定这个注册中心
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      perferIpAddress: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
